### ISSUE TITLE
CHG make the landing page better

### ISSUE THREAD

**Issue by wabscale** [GusSand/Anubis#116]
The current landing page could use some improvements. It was written by me, which means it is simple as it can be. I am not a frontend / web design person so I could use some more keen eyes on this one.

![Screenshot 2021-06-25 at 22-51-39 Anubis](https://user-images.githubusercontent.com/36013983/123499918-08c2d200-d608-11eb-9909-34212580b6db.png)

p.s. The nav on the left is cut off because I used the firefox "screenshot of full page" feature. It is not actually getting messed up.

**Comment by AlpacaMax** [comment]
I personally think it's time to completely redesign the UI for Anubis. The current one is usable but not appealing(at least for me).

**Comment by nysteo** [comment]
> I personally think it's time to completely redesign the UI for Anubis. The current one is usable but not appealing(at least for me).

We are working on that [check it out](https://github.com/GusSand/Anubis/issues/119)

**Comment by AlpacaMax** [comment]
I thought that's a separate marketing page? I like the new logo and color scheme though

**Comment by nysteo** [comment]
> I thought that's a separate marketing page? I like the new logo and color scheme though

In pages if you go to 'application' I started redesigning the application UI as well. Hopefully will be done with it tomorrow.

**Comment by nysteo** [comment]
This is replaced by #119
