### ISSUE TITLE
ADD export student answers to autograde results 

### ISSUE THREAD

**Issue by wabscale** [GusSand/Anubis#186]
This should be for a single student or the whole class. We should build a directory of netids where the most recent question responses are dumped, zip the whole thing up, then give it back to the TA requesting.

```
abc123/
  `- abc123.txt  # Meta file with datetimes for submissions
  `- question1.txt
  `- response1.txt
  `- question2.txt
  `- response2.txt
xyz789/
  `- xyz789.txt
  `- question1.txt
  `- response1.txt
  `- question2.txt
  `- response2.txt
...
```

**Comment by GusSand** [comment]
That would work unless there's a way to have a PDF file? 

thanks for being proactive about this.

**Comment by wabscale** [comment]
So I forgot that we actually already sort of have this functionality. You can export all student questions as a JSON file, but it is in a bit of a weird place. I have added the zip file export thing as described above. 

I have looked in the past and did not find any good solutions for generating pdfs. It would probably be pretty much the same as throwing all of it into a txt file. I will look again to see if there is something that fits our needs.
