### ISSUE TITLE
ADD github SSO for linking github account

### ISSUE THREAD

**Issue by wabscale** [GusSand/Anubis#240]

**Comment by AlpacaMax** [comment]
Is this basically adding a login through github option?

**Comment by wabscale** [comment]
Not authentication for Anubis itself. This would be for linking the github account. We've been having quite a few issues this semester from people putting in an incorrect github username into Anubis. Forcing them to link through github would pretty much eliminate this problem. We would be able to guarantee that the github account exists, and actually belongs to the user.

**Comment by AlpacaMax** [comment]
I think I can add this feature. So basically we need to change the original github username input box into a `Link to My Github Account` button or something like that. When student click it it will redirect to the authorization page on github. After authorization it redirects back to Anubis with the `access_token`. Then we use this token to access the github username and store it into the database. Is that how it works?

**Comment by wabscale** [comment]
Yes. In theory you should be able to use / extend / copy paste the SSO junk we currently use for authenticating with NYU. Just please be careful to not put any client id or client secret things in any commits.
