### ISSUE TITLE
CHG make mkdebug target independent of the git kubernetes secret

### ISSUE THREAD

**Issue by wabscale** [GusSand/Anubis#261]

**Comment by PIG208** [comment]
Actually, I think we shouldn't make it independent to git secrets. Perhaps it would be better to do something similar to what we have for the `oauth` secrets (putting some defaults to the provision script for git secret setup). Or even better: create `init-secrets-template.sh` and enforce the user to edit and rename it to `init-secrets.sh` before we get to run the provision script.

**Comment by PIG208** [comment]
There are still some problems to be solved to make `make mkdebug` out of the box. #262 resolves the problem of missing the `git` secret. As a follow-up, we also need to solve the theia image issue.
